# Generated by Django 4.0.4 on 2022-05-24 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='No name', max_length=200)),
                ('price', models.FloatField(default=0)),
                ('description', models.CharField(default='No description', max_length=500)),
                ('created_at', models.DateField(blank=True, null=True)),
                ('num_pages', models.IntegerField(default=0)),
                ('genre', models.CharField(default='No genre', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='No name', max_length=200)),
                ('price', models.FloatField(default=0)),
                ('description', models.CharField(default='No description', max_length=500)),
                ('created_at', models.DateField(blank=True, null=True)),
                ('type', models.CharField(choices=[('B', 'BULLET'), ('F', 'FOOD'), ('T', 'TRAVEL'), ('S', 'SPORT')], default='B', max_length=2)),
                ('publisher', models.CharField(max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
