# Generated by Django 4.0.4 on 2022-05-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile_groups_userprofile_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
